; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:door_esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<*> -<main.cpp> -<controller_esp32.cpp> -<door_system.cpp>
lib_deps = 
	adafruit/Adafruit ILI9341@^1.6.2
	paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
	bodmer/TFT_eSPI@^2.5.43
	miguelbalboa/MFRC522@^1.4.12
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.0
	bblanchon/ArduinoJson@^6.21.3
	Keypad
build_flags = 
	-DUSER_SETUP_LOADED=1
	-include "User_Setup.h"
check_tool = cppcheck
check_flags = 
	cppcheck: --enable=all --include-path=include/

[env:controller_esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<*> -<main.cpp> -<door_system.cpp> -<door_system_main.cpp>

[env:display_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<main.cpp> -<*>
lib_deps = 
	adafruit/Adafruit ILI9341@^1.6.2
	paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
	bodmer/TFT_eSPI@^2.5.43
build_flags = 
	-DUSER_SETUP_LOADED=1
	-include "User_Setup.h"

; Test environments
[env:test_tft]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_tft_display.cpp> -<*>
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
build_flags = 
	-DUSER_SETUP_LOADED=1
	-include "User_Setup.h"

[env:test_fingerprint]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_fingerprint.cpp> -<*>
lib_deps = 
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.0

[env:test_rfid]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_rfid.cpp> -<*>
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12

[env:test_esp_now]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_esp_now.cpp> -<*>

[env:test_relay]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_relay.cpp> -<*>

[env:test_wifi_api]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_wifi_api.cpp> -<*>
lib_deps = 
	bblanchon/ArduinoJson@^6.21.3

[env:test_keypad]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_keypad_touch.cpp> -<*>
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
build_flags = 
	-DUSER_SETUP_LOADED=1
	-include "User_Setup.h"

[env:rfid_test_2]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/rfid_test_2.cpp> -<*>
lib_deps = 
	miguelbalboa/MFRC522@^1.4.12

[env:test_touch_debug]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_touch_debug.cpp> -<*>
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	paulstoffregen/XPT2046_Touchscreen@0.0.0-alpha+sha.26b691b2c8
build_flags = 
	-DUSER_SETUP_LOADED=1
	-include "User_Setup.h"

[env:test_physical_keypad]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_physical_keypad.cpp> -<*>
lib_deps = 
	Keypad

[env:test_mac_address]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_mac_address.cpp> -<*>

[env:test_enroll_print]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_enroll_print.cpp> -<*>
lib_deps = 
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.0

[env:test_espnow]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_espnow_communication.cpp> -<*>
lib_deps = 
	adafruit/Adafruit Fingerprint Sensor Library@^2.1.0

[env:test_espnow_tx]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_espnow_master.cpp> -<*>

[env:test_espnow_rx]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_src_filter = +<../test/test_espnow_slave.cpp> -<*>